from pathlib import Path


class ReportGenerator:
    """Generate analysis reports"""
    
    @staticmethod
    def generate(model_info, analysis, improvements, issues):
        """Generate complete report"""
        
        report = f"""
╔═══════════════════════════════════════════════════════════════╗
║                   MODEL ANALYSIS REPORT                       ║
╚═══════════════════════════════════════════════════════════════╝

📊 MODEL INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Type:       {model_info.get('type', 'Unknown')}
Layers:     {model_info.get('layers', 'Unknown')}
Parameters: {model_info.get('parameters', 'Unknown')}

❌ ISSUES FOUND
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
        
        if issues:
            for issue in issues:
                report += f"\n• [{issue.get('severity', 'info')}] {issue.get('message', 'Unknown issue')}"
                report += f"\n  Fix: {issue.get('fix', 'No fix provided')}\n"
        else:
            report += "\n✅ No major issues detected!\n"
        
        report += f"""
🔍 ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{analysis}

💡 IMPROVEMENTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{improvements}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by ModelMind
"""
        
        return report
    
    @staticmethod
    def save_report(report_text, filename="report.txt"):
        """Save report to file"""
        output_dir = Path("storage/reports")
        output_dir.mkdir(parents=True, exist_ok=True)
        
        filepath = output_dir / filename
        with open(filepath, 'w') as f:
            f.write(report_text)
        
        return str(filepath)
